SELECT *
FROM PORTFOLIOPROJECT..COVID_DEATHS
WHERE CONTINENT IS NOT NULL
ORDER BY 3, 4

--SELECT *
--FROM PORTFOLIOPROJECT..COVID_VACCINATION
--ORDER BY 3, 4

-- SELECT DATA THAT WE ARE GOING TO BE USING

SELECT LOCATION, DATE, TOTAL_CASES, NEW_CASES, TOTAL_DEATHS, POPULATION
FROM PORTFOLIOPROJECT..COVID_DEATHS
ORDER BY 1, 2


--LOOKING AT TOTAL CASES VS TOTAL DEATHS

SELECT LOCATION, DATE, TOTAL_CASES, TOTAL_DEATHS, (TOTAL_DEATHS/TOTAL_CASES)* 100 AS DEATHPERCENT
FROM PORTFOLIOPROJECT..COVID_DEATHS
WHERE LOCATION LIKE '%india%'
ORDER BY 1, 2

-- LOOKING AT TOTAL CASES VS POPULATION
--SHOWS WHAT PERCENT OF POPULATION GOT COVID

SELECT LOCATION, DATE, TOTAL_CASES, POPULATION, (TOTAL_CASES/POPULATION)* 100 AS DEATHPERCENT
FROM PORTFOLIOPROJECT..COVID_DEATHS
WHERE LOCATION LIKE '%india%'
ORDER BY 1, 2


--LOOKING AT COUNTRIES WITH HIGHEST INFECTION RATE

SELECT LOCATION, POPULATION, MAX(TOTAL_CASES) AS HIGHESTINFECTIONCOUNT,MAX((TOTAL_CASES/POPULATION))* 100 AS INFECTEDPERCENT
FROM PORTFOLIOPROJECT..COVID_DEATHS
GROUP BY LOCATION, POPULATION
ORDER BY 4 DESC


--SHOWING COUNTRIES WITH HIGHEST DEATH COUNT PER POPULATION

SELECT LOCATION, MAX(CAST(TOTAL_DEATHS AS BIGINT)) AS TOTALDEATHS
FROM PORTFOLIOPROJECT..COVID_DEATHS
WHERE CONTINENT IS NOT NULL
GROUP BY LOCATION
ORDER BY 2 DESC


-- LET'S BREAK BY CONTINENT

SELECT CONTINENT, MAX(CAST(TOTAL_DEATHS AS BIGINT)) AS TOTALDEATHS
FROM PORTFOLIOPROJECT..COVID_DEATHS
WHERE CONTINENT IS NOT NULL
GROUP BY CONTINENT
ORDER BY 2 DESC

-- SHOWING CONTINENTS BY HIGHEST DEATH COUNTS

SELECT CONTINENT, MAX(CAST(TOTAL_DEATHS AS BIGINT)) AS TOTALDEATHS
FROM PORTFOLIOPROJECT..COVID_DEATHS
WHERE CONTINENT IS NOT NULL
GROUP BY CONTINENT
ORDER BY 2 DESC


-- GLOBAL NUMBERS

SELECT SUM(NEW_CASES) AS CASES, SUM(CAST(NEW_DEATHS AS BIGINT)) AS DEATHS, 
(SUM(CAST(NEW_DEATHS AS BIGINT))/SUM(NEW_CASES))*100 AS DEATHPERCENT
FROM PORTFOLIOPROJECT..COVID_DEATHS
WHERE CONTINENT IS NOT NULL
--GROUP BY DATE
ORDER BY 1, 2


-- LOOKING AT TOTAL POPULATION AND VACCINATION

SELECT D.CONTINENT, D.LOCATION, D.DATE, D.POPULATION, V.NEW_VACCINATIONS
FROM PORTFOLIOPROJECT..COVID_DEATHS D
JOIN PORTFOLIOPROJECT..COVID_VACCINATION V
	ON D.LOCATION = V.LOCATION
	AND D.DATE = V.DATE
WHERE D.CONTINENT IS NOT NULL
ORDER BY 2, 3


-- ROLLING SUM 

SELECT D.CONTINENT, D.LOCATION, D.DATE, D.POPULATION, V.NEW_VACCINATIONS
, SUM(CAST(V.NEW_VACCINATIONS AS BIGINT)) OVER (PARTITION BY D.LOCATION ORDER BY D.LOCATION,
D.DATE) AS ROLLINGSUMVACCINATION
FROM PORTFOLIOPROJECT..COVID_DEATHS D
JOIN PORTFOLIOPROJECT..COVID_VACCINATION V
	ON D.LOCATION = V.LOCATION
	AND D.DATE = V.DATE
WHERE D.CONTINENT IS NOT NULL
ORDER BY 2, 3

-- USE CTE

WITH POPVSVAC (CONTINENT, LOCATION, DATE, POPULATION, NEW_VACCINATION, ROLLINGSUMVACCINATION)
AS
(
SELECT D.CONTINENT, D.LOCATION, D.DATE, D.POPULATION, V.NEW_VACCINATIONS
, SUM(CAST(V.NEW_VACCINATIONS AS BIGINT)) OVER (PARTITION BY D.LOCATION ORDER BY D.LOCATION,
D.DATE) AS ROLLINGSUMVACCINATION
FROM PORTFOLIOPROJECT..COVID_DEATHS D
JOIN PORTFOLIOPROJECT..COVID_VACCINATION V
	ON D.LOCATION = V.LOCATION
	AND D.DATE = V.DATE
WHERE D.CONTINENT IS NOT NULL
--ORDER BY 2, 3
)

SELECT *, (ROLLINGSUMVACCINATION/POPULATION)*100
FROM POPVSVAC


-- TEMP TABLE
DROP TABLE IF EXISTS #PERCENTPOPULATIONVACCINATED
CREATE TABLE #PERCENTPOPULATIONVACCINATED
(
CONTINENT NVARCHAR(255),
LOCATION NVARCHAR(255),
DATE DATETIME, 
POPULATION NUMERIC, 
NEW_VACCINATIONS NUMERIC, 
ROLLINGPEOPLEVACCINATED NUMERIC
)

INSERT INTO #PERCENTPOPULATIONVACCINATED
SELECT D.CONTINENT, D.LOCATION, D.DATE, D.POPULATION, V.NEW_VACCINATIONS
, SUM(CAST(V.NEW_VACCINATIONS AS BIGINT)) OVER (PARTITION BY D.LOCATION ORDER BY D.LOCATION,
D.DATE) AS ROLLINGSUMVACCINATION
FROM PORTFOLIOPROJECT..COVID_DEATHS D
JOIN PORTFOLIOPROJECT..COVID_VACCINATION V
	ON D.LOCATION = V.LOCATION
	AND D.DATE = V.DATE
--WHERE D.CONTINENT IS NOT NULL
--ORDER BY 2, 3

SELECT *, (ROLLINGPEOPLEVACCINATED/POPULATION)*100
FROM #PERCENTPOPULATIONVACCINATED


-- CREATE VIEW
DROP VIEW IF EXISTS PERCENTPOPULATIONVACCINATED
CREATE VIEW  PERCENTPOPULATIONVACCINATED AS
SELECT D.CONTINENT, D.LOCATION, D.DATE, D.POPULATION, V.NEW_VACCINATIONS
, SUM(CAST(V.NEW_VACCINATIONS AS BIGINT)) OVER (PARTITION BY D.LOCATION ORDER BY D.LOCATION,
D.DATE) AS ROLLINGSUMVACCINATION
FROM PORTFOLIOPROJECT..COVID_DEATHS D
JOIN PORTFOLIOPROJECT..COVID_VACCINATION V
	ON D.LOCATION = V.LOCATION
	AND D.DATE = V.DATE
WHERE D.CONTINENT IS NOT NULL
--ORDER BY 2, 3

-- ACCESSING THE VIEW
SELECT * 
FROM PERCENTPOPULATIONVACCINATED 